### ISSUE TITLE
Conflict between pxtlib USB Type Declaration and @types/w3c-web-usb dependency in dapjs

### ISSUE THREAD

**Issue by nedseb** [microsoft/pxt#10259]
I experienced a TypeScript compilation error when using `dapjs` as a dependency for the [STeaMi Makecode editor](https://github.com/steamicc/makecode-steami) built with `pxt`. 

The issue appears to be a conflict in the declaration of the `usb` property in the `Navigator` interface between `pxtlib/webusb.ts` and `@types/w3c-web-usb`, which is used by `dapjs`.

Seems related to the modification introduced by PR #10146.

 Here are the details:

### Error Description

When compiling my project, I got the following errors:

```
../node_modules/@types/w3c-web-usb/index.d.ts:171:14 - error TS2687: All declarations of 'usb' must have identical modifiers.

171     readonly usb: USB;
                 ~~~

../node_modules/@types/w3c-web-usb/index.d.ts:171:14 - error TS2717: Subsequent property declarations must have the same type. Property 'usb' must be of type '{ getDevices(): Promise<USBDevice[]>; requestDevice(options?: USBDeviceRequestOptions): Promise<USBDevice>; addEventListener(type: "connect" | "disconnect", listener: (ev: USBConnectionEvent) => any, useCapture?: boolean): void; removeEventListener(type: "connect" | "disconnect", callback: (ev: USBConnectionEvent) =...', but here has type 'USB'.

171     readonly usb: USB;
                 ~~~

  ../../pxt/built/pxtlib.d.ts:3379:14
    3379     readonly usb?: {
                      ~~~
    'usb' was also declared here.

../../pxt/built/pxtlib.d.ts:3379:14 - error TS2687: All declarations of 'usb' must have identical modifiers.

3379     readonly usb?: {
                  ~~~
```

### Context

- The compilation issue is caused by a conflict in the type declarations of the `usb` property in the `Navigator` interface.
- In `pxtlib.d.ts` (generated from `pxt`), we have the following declaration:

  ```typescript
  interface Navigator {
      readonly usb?: {
          getDevices(): Promise<pxt.usb.USBDevice[]>;
          requestDevice(options?: pxt.usb.USBDeviceRequestOptions): Promise<pxt.usb.USBDevice>;
          addEventListener(
              type: "connect" | "disconnect",
              listener: (ev: pxt.usb.USBConnectionEvent) => any,
              useCapture?: boolean,
          ): void;
          removeEventListener(
              type: "connect" | "disconnect",
              callback: (ev: pxt.usb.USBConnectionEvent) => any,
              useCapture?: boolean,
          ): void;
      }
  }
  ```

- Meanwhile, `@types/w3c-web-usb` defines:

  ```typescript
  interface Navigator {
      readonly usb: USB;
  }

declare class USB extends EventTarget {
    onconnect: ((this: this, ev: USBConnectionEvent) => any) | null;
    ondisconnect: ((this: this, ev: USBConnectionEvent) => any) | null;
    getDevices(): Promise<USBDevice[]>;
    requestDevice(options?: USBDeviceRequestOptions): Promise<USBDevice>;
    addEventListener(
        type: "connect" | "disconnect",
        listener: (this: this, ev: USBConnectionEvent) => any,
        useCapture?: boolean,
    ): void;
    addEventListener(
        type: string,
        listener: EventListenerOrEventListenerObject | null,
        options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener(
        type: "connect" | "disconnect",
        callback: (this: this, ev: USBConnectionEvent) => any,
        useCapture?: boolean,
    ): void;
    removeEventListener(
        type: string,
        callback: EventListenerOrEventListenerObject | null,
        options?: EventListenerOptions | boolean,
    ): void;
}
  ```

- The discrepancy arises from:
  - The `usb` property is optional (`usb?:`) in `pxtlib.d.ts`, while it is defined as non-optional (`usb: USB`) in `@types/w3c-web-usb`.
  - The type definitions themselves are incompatible (`USB` vs a custom structure).

### Impact

This conflict prevents projects that rely on both `pxt` and `dapjs` from compiling correctly. On the microbit editor, dapjs is directly inside the repo but it's not my favorite option, even if it could be a temporary workaround solution.

Please let me know if there are any planned changes or recommendations on how best to proceed.

Thank you for your time to read.
