### ISSUE TITLE
"pxt staticpkg" fails after 3f639e0

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#2085]
`pxt staticpkg` command fails after 3f639e0. @mmoskal 

```
packaging editor to built/packaged
libs/core/shims.d.ts(35,25): error TS2304: Cannot find name 'int32'.
libs/core/shims.d.ts(44,24): error TS2304: Cannot find name 'int32'.
libs/core/shims.d.ts(44,42): error TS2304: Cannot find name 'int32'.
   :
```
```
building sim...
[run] cd sim; node ../node_modules/typescript/bin/tsc
../libs/core/shims.d.ts(35,25): error TS2304: Cannot find name 'int32'.
../libs/core/shims.d.ts(44,24): error TS2304: Cannot find name 'int32'.
../libs/core/shims.d.ts(44,42): error TS2304: Cannot find name 'int32'.
   :
INTERNAL ERROR: Error: Exit code: 2 from cd sim; node ../node_modules/typescript/bin/tsc
    at ChildProcess.<anonymous> (/opt/pxt/built/nodeutil.js:85:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by pelikhan** [comment]
@mmoskal I wonder if the build optimization to skip projects also skips the regeneration of shims.d.ts.

**Comment by mmoskal** [comment]
@sgk first, you should build microbit against v0; master will soon stop working completely due to float changes
@pelikhan thou shall never use `shims.d.ts` in the simulator; fixed in https://github.com/Microsoft/pxt-microbit/commit/00bf5e52d7b728f011dab4508f9e410367104ca1
the `int32` is correct and defined in `pxt-core.d.ts`
